//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kadri
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Анкеты.
    /// </summary>
    // *** Start programmer edit section *** (Анкеты CustomAttributes)

    // *** End programmer edit section *** (Анкеты CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АнкетыE", new string[] {
            "ID as \'ID\'",
            "ЛК as \'ЛК\'",
            "ФИО as \'ФИО\'",
            "Контакты as \'Контакты\'",
            "Образование as \'Образование\'",
            "Опыт_работы as \'Опыт_работы\'",
            "Должность as \'Должность\'",
            "Должность.Название as \'Название\'"}, Hidden=new string[] {
            "Должность.Название"})]
    [MasterViewDefineAttribute("АнкетыE", "Должность", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [View("АнкетыL", new string[] {
            "ID as \'ID\'",
            "ЛК as \'ЛК\'",
            "ФИО as \'ФИО\'",
            "Контакты as \'Контакты\'",
            "Образование as \'Образование\'",
            "Опыт_работы as \'Опыт_работы\'",
            "Должность.Название as \'Название\'"})]
    public class Анкеты : IIS.Kadri.Физ_лица
    {
        
        private int fID;
        
        private string fЛК;
        
        private IIS.Kadri.Должности fДолжность;
        
        // *** Start programmer edit section *** (Анкеты CustomMembers)

        // *** End programmer edit section *** (Анкеты CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.ID CustomAttributes)

        // *** End programmer edit section *** (Анкеты.ID CustomAttributes)
        [NotNull()]
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.ID Get start)

                // *** End programmer edit section *** (Анкеты.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Анкеты.ID Get end)

                // *** End programmer edit section *** (Анкеты.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.ID Set start)

                // *** End programmer edit section *** (Анкеты.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Анкеты.ID Set end)

                // *** End programmer edit section *** (Анкеты.ID Set end)
            }
        }
        
        /// <summary>
        /// ЛК.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.ЛК CustomAttributes)

        // *** End programmer edit section *** (Анкеты.ЛК CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string ЛК
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.ЛК Get start)

                // *** End programmer edit section *** (Анкеты.ЛК Get start)
                string result = this.fЛК;
                // *** Start programmer edit section *** (Анкеты.ЛК Get end)

                // *** End programmer edit section *** (Анкеты.ЛК Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.ЛК Set start)

                // *** End programmer edit section *** (Анкеты.ЛК Set start)
                this.fЛК = value;
                // *** Start programmer edit section *** (Анкеты.ЛК Set end)

                // *** End programmer edit section *** (Анкеты.ЛК Set end)
            }
        }
        
        /// <summary>
        /// Анкеты.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.Должность CustomAttributes)

        // *** End programmer edit section *** (Анкеты.Должность CustomAttributes)
        [PropertyStorage(new string[] {
                "Должность"})]
        [NotNull()]
        public virtual IIS.Kadri.Должности Должность
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.Должность Get start)

                // *** End programmer edit section *** (Анкеты.Должность Get start)
                IIS.Kadri.Должности result = this.fДолжность;
                // *** Start programmer edit section *** (Анкеты.Должность Get end)

                // *** End programmer edit section *** (Анкеты.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.Должность Set start)

                // *** End programmer edit section *** (Анкеты.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (Анкеты.Должность Set end)

                // *** End programmer edit section *** (Анкеты.Должность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АнкетыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АнкетыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АнкетыE", typeof(IIS.Kadri.Анкеты));
                }
            }
            
            /// <summary>
            /// "АнкетыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АнкетыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АнкетыL", typeof(IIS.Kadri.Анкеты));
                }
            }
        }
    }
}
