//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kadri
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудники.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудники CustomAttributes)

    // *** End programmer edit section *** (Сотрудники CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникиE", new string[] {
            "ID as \'ID\'",
            "Дата_приема as \'Дата_приема\'",
            "ФИО as \'ФИО\'",
            "Контакты as \'Контакты\'",
            "Образование as \'Образование\'",
            "Опыт_работы as \'Опыт_работы\'",
            "Отдел as \'Отдел\'",
            "Отдел.Название as \'Название\'",
            "Должность as \'Должность\'",
            "Должность.Название as \'Название\'"}, Hidden=new string[] {
            "Отдел.Название",
            "Должность.Название"})]
    [MasterViewDefineAttribute("СотрудникиE", "Отдел", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("СотрудникиE", "Должность", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [View("СотрудникиL", new string[] {
            "ID as \'ID\'",
            "Дата_приема as \'Дата_приема\'",
            "ФИО as \'ФИО\'",
            "Контакты as \'Контакты\'",
            "Образование as \'Образование\'",
            "Опыт_работы as \'Опыт_работы\'",
            "Отдел.Название as \'Название\'",
            "Должность.Название as \'Название\'"})]
    public class Сотрудники : IIS.Kadri.Физ_лица
    {
        
        private int fID;
        
        private System.DateTime fДата_приема;
        
        private IIS.Kadri.Отделы fОтдел;
        
        private IIS.Kadri.Должности fДолжность;
        
        // *** Start programmer edit section *** (Сотрудники CustomMembers)

        // *** End programmer edit section *** (Сотрудники CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.ID CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.ID Get start)

                // *** End programmer edit section *** (Сотрудники.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Сотрудники.ID Get end)

                // *** End programmer edit section *** (Сотрудники.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.ID Set start)

                // *** End programmer edit section *** (Сотрудники.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Сотрудники.ID Set end)

                // *** End programmer edit section *** (Сотрудники.ID Set end)
            }
        }
        
        /// <summary>
        /// Дата_приема.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Дата_приема CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Дата_приема CustomAttributes)
        public virtual System.DateTime Дата_приема
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Дата_приема Get start)

                // *** End programmer edit section *** (Сотрудники.Дата_приема Get start)
                System.DateTime result = this.fДата_приема;
                // *** Start programmer edit section *** (Сотрудники.Дата_приема Get end)

                // *** End programmer edit section *** (Сотрудники.Дата_приема Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Дата_приема Set start)

                // *** End programmer edit section *** (Сотрудники.Дата_приема Set start)
                this.fДата_приема = value;
                // *** Start programmer edit section *** (Сотрудники.Дата_приема Set end)

                // *** End programmer edit section *** (Сотрудники.Дата_приема Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Должность CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Должность CustomAttributes)
        [PropertyStorage(new string[] {
                "Должность"})]
        [NotNull()]
        public virtual IIS.Kadri.Должности Должность
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Должность Get start)

                // *** End programmer edit section *** (Сотрудники.Должность Get start)
                IIS.Kadri.Должности result = this.fДолжность;
                // *** Start programmer edit section *** (Сотрудники.Должность Get end)

                // *** End programmer edit section *** (Сотрудники.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Должность Set start)

                // *** End programmer edit section *** (Сотрудники.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (Сотрудники.Должность Set end)

                // *** End programmer edit section *** (Сотрудники.Должность Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Отдел CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Отдел CustomAttributes)
        [PropertyStorage(new string[] {
                "Отдел"})]
        [NotNull()]
        public virtual IIS.Kadri.Отделы Отдел
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Отдел Get start)

                // *** End programmer edit section *** (Сотрудники.Отдел Get start)
                IIS.Kadri.Отделы result = this.fОтдел;
                // *** Start programmer edit section *** (Сотрудники.Отдел Get end)

                // *** End programmer edit section *** (Сотрудники.Отдел Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Отдел Set start)

                // *** End programmer edit section *** (Сотрудники.Отдел Set start)
                this.fОтдел = value;
                // *** Start programmer edit section *** (Сотрудники.Отдел Set end)

                // *** End programmer edit section *** (Сотрудники.Отдел Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиE", typeof(IIS.Kadri.Сотрудники));
                }
            }
            
            /// <summary>
            /// "СотрудникиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиL", typeof(IIS.Kadri.Сотрудники));
                }
            }
        }
    }
}
