//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kadri
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Физ_лица.
    /// </summary>
    // *** Start programmer edit section *** (Физ_лица CustomAttributes)

    // *** End programmer edit section *** (Физ_лица CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Физ_лицаE", new string[] {
            "ФИО as \'ФИО\'",
            "Контакты as \'Контакты\'",
            "Образование as \'Образование\'",
            "Опыт_работы as \'Опыт_работы\'"})]
    [View("Физ_лицаL", new string[] {
            "ФИО as \'ФИО\'",
            "Контакты as \'Контакты\'",
            "Образование as \'Образование\'",
            "Опыт_работы as \'Опыт_работы\'"})]
    public class Физ_лица : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private string fКонтакты;
        
        private string fОбразование;
        
        private string fОпыт_работы;
        
        // *** Start programmer edit section *** (Физ_лица CustomMembers)

        // *** End programmer edit section *** (Физ_лица CustomMembers)

        
        /// <summary>
        /// Контакты.
        /// </summary>
        // *** Start programmer edit section *** (Физ_лица.Контакты CustomAttributes)

        // *** End programmer edit section *** (Физ_лица.Контакты CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Контакты
        {
            get
            {
                // *** Start programmer edit section *** (Физ_лица.Контакты Get start)

                // *** End programmer edit section *** (Физ_лица.Контакты Get start)
                string result = this.fКонтакты;
                // *** Start programmer edit section *** (Физ_лица.Контакты Get end)

                // *** End programmer edit section *** (Физ_лица.Контакты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Физ_лица.Контакты Set start)

                // *** End programmer edit section *** (Физ_лица.Контакты Set start)
                this.fКонтакты = value;
                // *** Start programmer edit section *** (Физ_лица.Контакты Set end)

                // *** End programmer edit section *** (Физ_лица.Контакты Set end)
            }
        }
        
        /// <summary>
        /// Образование.
        /// </summary>
        // *** Start programmer edit section *** (Физ_лица.Образование CustomAttributes)

        // *** End programmer edit section *** (Физ_лица.Образование CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Образование
        {
            get
            {
                // *** Start programmer edit section *** (Физ_лица.Образование Get start)

                // *** End programmer edit section *** (Физ_лица.Образование Get start)
                string result = this.fОбразование;
                // *** Start programmer edit section *** (Физ_лица.Образование Get end)

                // *** End programmer edit section *** (Физ_лица.Образование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Физ_лица.Образование Set start)

                // *** End programmer edit section *** (Физ_лица.Образование Set start)
                this.fОбразование = value;
                // *** Start programmer edit section *** (Физ_лица.Образование Set end)

                // *** End programmer edit section *** (Физ_лица.Образование Set end)
            }
        }
        
        /// <summary>
        /// Опыт_работы.
        /// </summary>
        // *** Start programmer edit section *** (Физ_лица.Опыт_работы CustomAttributes)

        // *** End programmer edit section *** (Физ_лица.Опыт_работы CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Опыт_работы
        {
            get
            {
                // *** Start programmer edit section *** (Физ_лица.Опыт_работы Get start)

                // *** End programmer edit section *** (Физ_лица.Опыт_работы Get start)
                string result = this.fОпыт_работы;
                // *** Start programmer edit section *** (Физ_лица.Опыт_работы Get end)

                // *** End programmer edit section *** (Физ_лица.Опыт_работы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Физ_лица.Опыт_работы Set start)

                // *** End programmer edit section *** (Физ_лица.Опыт_работы Set start)
                this.fОпыт_работы = value;
                // *** Start programmer edit section *** (Физ_лица.Опыт_работы Set end)

                // *** End programmer edit section *** (Физ_лица.Опыт_работы Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Физ_лица.ФИО CustomAttributes)

        // *** End programmer edit section *** (Физ_лица.ФИО CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Физ_лица.ФИО Get start)

                // *** End programmer edit section *** (Физ_лица.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Физ_лица.ФИО Get end)

                // *** End programmer edit section *** (Физ_лица.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Физ_лица.ФИО Set start)

                // *** End programmer edit section *** (Физ_лица.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Физ_лица.ФИО Set end)

                // *** End programmer edit section *** (Физ_лица.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Физ_лицаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Физ_лицаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Физ_лицаE", typeof(IIS.Kadri.Физ_лица));
                }
            }
            
            /// <summary>
            /// "Физ_лицаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Физ_лицаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Физ_лицаL", typeof(IIS.Kadri.Физ_лица));
                }
            }
        }
    }
}
